### ISSUE TITLE
[Submission]: 

### ISSUE THREAD

**Issue by Alestarov** [YimMenu-Lua/submission#21]
### Repository Name

Alestarov Menu

### Description

# Alestarov_Menu_V2b_1.67
![](https://img.shields.io/badge/dynamic/json?color=ffab00&label=Online%20Version&query=%24.game.online&url=https%3A%2F%2Fraw.githubusercontent.com%2FYimMenu%2FYimMenu%2Fmaster%2Fmetadata.json&style=flat-square&labelColor=000000) ![](https://img.shields.io/badge/dynamic/json?color=ffab00&label=Game%20Build&query=%24.game.build&url=https%3A%2F%2Fraw.githubusercontent.com%2FYimMenu%2FYimMenu%2Fmaster%2Fmetadata.json&style=flat-square&labelColor=000000)

*Code from other scripts can be used in this script. All links to scripts and copyright holders are in the section "Credits"*

 *By using my script you agree to the User Agreement*
## Yim Menu

* [Download Yim Menu](https://github.com/YimMenu/YimMenu)

## Before using the Script, watch the Video Instruction!
* [Video Instruction](https://youtu.be/rSr5O3diAwk)

This script was created for the Yim Menu cheat.

This cheat contains the best ways to cheat currency in GTA 5 online.

Also in this cheat there is a Stat editor for account security, and many other functions...

The script will be supplemented, about all the changes will be written here

# New
## Heist editor:

Cayo Perico Heist

Fleeca Heist

Casino Heist

## CMM Menu
(Computers Management Menu)

# User Agreement

Use agreement：

When editing the Script, please indicate the authors

# Instructions for AlMenu
![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/3fe3db2c-592b-4fbb-9209-e9d141ee134f)

![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/5780416d-1af6-4c0f-bb20-4f7b45c49348)

## Almenu Interface

![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/e7224602-f270-4406-812f-6dce1ab7f721)

## Misc Interface

![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/f17574ac-d1ce-4d89-b579-b86a7b838d33)

## Teleport Interface

![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/114df4b5-3b18-4d79-900a-8fbe1e93fcca)

## CMM Interface

(Computers Management Menu)

![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/20e60b05-9e08-42d4-aaaa-561102816d37)

## Money Interface

![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/1a1b47ea-1b65-4212-9b26-a1725a777f56)

 CEO
 
![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/f51b692b-8dc6-4e97-9f38-5b43360345a4)

 Casino
 
![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/4d1c4e25-d569-4865-a200-700e1fe77311)

## Heist Editor Interface

![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/58909366-a466-4fde-a771-1344d39b31c3)

Cayo Perico Heist

![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/927c23a7-c4d9-43d3-b1b0-fdecd7bf2545)

Fleeca Heist

![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/8ee878c3-267a-42ff-b96b-49cf032b7cb9)

Casino Heist

![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/5ad82976-cb01-4a00-82b3-411f77fa9a20)

## Stat Editor Interface

![image](https://github.com/Alestarov/YimMenu-lua-script-Alestarov_Menu/assets/108485130/79db794f-6938-4c8c-a0ed-98cb3bcda413)

# Credits

## 👑 Yimura 👑
(Yim Menu Cheat creator)

Cheat on GitHub:

https://github.com/YimMenu/YimMenu
## 👑 Alestarov 👑
(compiled a script)

Profile on GitHub:

https://github.com/Alestarov
## 👑sch-lda👑
(allowed to use the code from his script "SCH-LUA-YIMMENU.lua)

(The code from the script ''SCH-LUA-YIMMENU.lua'' was implemented)

Script on GitHub:

https://github.com/sch-lda/SCH-LUA-YIMMENU
## 👑 xiaoxiao921 👑
(Helped with writing code)

Profile on GitHub:

https://github.com/xiaoxiao921
## 👑 SLON 👑
(The code from the script ''YimCeo v0.3 by Slon_.lua'' was implemented)

Script on unknowncheats:

https://www.unknowncheats.me/forum/grand-theft-auto-v/591335-yimceo-ceo-crates-method-yimmenu.html
## 👑 gir489returns 👑
(The code from the script ''Casino Pacino.lua'' was implemented)

Script on GitHub:

https://github.com/YimMenu-Lua/Casino-Pacino/blob/main/CasinoPacino.lua

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by Yimura** [comment]
Try again by making a new issue with a shorter description, this can be modified afterwards.
