### ISSUE TITLE
[Submission]: 

### ISSUE THREAD

**Issue by Alestarov** [YimMenu-Lua/submission#22]
### Repository Name

Alestarov Menu

### Description

This is a lua build that contains the best ways to cheat Money, Clear statistics, Heist editor and much more. The script will be constantly updated. It contains the best features from other scripts.

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/Alestarov-Menu/invitations).
