### ISSUE TITLE
[Submission]: lua request

### ISSUE THREAD

**Issue by abuazizv** [YimMenu-Lua/submission#23]
### Repository Name

Pessi

### Description

Pessi is mainly a recovery script, with various methods, ranging from a 1M fast loop to various limited transactions

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/Pessi/invitations).
