### ISSUE TITLE
[Submission]: WeaponEditor

### ISSUE THREAD

**Issue by George0828Zhang** [YimMenu-Lua/submission#24]
### Repository Name

Weapon-Editor

### Description

WeaponEditor is a lua script that lets you mod weapons.meta externally while the game is running. You can mod weapon behaviour, add attachments etc. without actually changing the game files.

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/Weapon-Editor/invitations).
