### ISSUE TITLE
[Submission]: AcidLab

### ISSUE THREAD

**Issue by wanz1337** [YimMenu-Lua/submission#25]
### Repository Name

AcidLab

### Description

AcidLab is a simple Acid value changer booster of production and capacity of the product

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by Yimura** [comment]
@wanz1337, could you submit another issue this time without any ENTER's in the description? It seems the bot broke and failed to create a repository for you.
