### ISSUE TITLE
[Submission]: AcidLab

### ISSUE THREAD

**Issue by wanz1337** [YimMenu-Lua/submission#27]
### Repository Name

AcidLab Script

### Description

AcidLab_features_like_product_value_changer_capacity_changer_and_etc

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/AcidLab-Script/invitations).
