### ISSUE TITLE
[Submission]: Random Events

### ISSUE THREAD

**Issue by ShinyWasabi** [YimMenu-Lua/submission#30]
### Repository Name

RandomEvents

### Description

A Lua script for YimMenu about Random Events.

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/RandomEvents/invitations).
