### ISSUE TITLE
[Submission]: Utimate Menu For YimMenu

### ISSUE THREAD

**Issue by L7NEG** [YimMenu-Lua/submission#35]
### Repository Name

Utimate-Menu

### Description

Hello Its Me L7NEG Im Back Again With My Own Write Script Its Called Ultimate Menu For Kiddions Modest Menu & YimMenu A Trusted Menu Made With Love To You All

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/Utimate-Menu/invitations).
