### ISSUE TITLE
[Submission]: Ground Fireworks

### ISSUE THREAD

**Issue by tupoy-ya** [YimMenu-Lua/submission#38]
### Repository Name

GroundFireworks

### Description

Adds ground fireworks that work similar to ground fireworks from old GTA Online

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/GroundFireworks/invitations).
