### ISSUE TITLE
[Submission]: Harmless's Lua Scripts

### ISSUE THREAD

**Issue by Harmless05** [YimMenu-Lua/submission#42]
### Repository Name

Harmless-Scripts

### Description

Repo for Lua scripts made by Harmless for YimMenu

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/Harmless-Scripts/invitations).
