### ISSUE TITLE
[Submission]: 

### ISSUE THREAD

**Issue by xesdoog** [YimMenu-Lua/submission#43]
### Repository Name

SAMURAI-Scenarios

### Description

Lua script to play GTA Online scenarios using YimMenu.

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/SAMURAI-Scenarios/invitations).
