### ISSUE TITLE
[Submission]: Mini game hack lua

### ISSUE THREAD

**Issue by sch-lda** [YimMenu-Lua/submission#46]
### Repository Name

MiniGameHack

### Description

Minigame instant complete, skip hacking process

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/MiniGameHack/invitations).
