### ISSUE TITLE
[Submission]: Extras Addon

### ISSUE THREAD

**Issue by Deadlineem** [YimMenu-Lua/submission#51]
### Repository Name

Extras-Addon-for-YimMenu

### Description

All in one multi-tool script for YimMenu

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by dopetheking** [comment]
ı agree all

**Comment by lYoril** [comment]
Repository Name
Extras-Addon-for-YimMenu

Description
All in one multi-tool script for YimMenu

ToS Agreement
 I agree to the Github ToS
External Linking
 I agree not to link externally
No Advertising
 I agree not to advertise for commercial gain
Paywalling
 I agree not to paywall features
