### ISSUE TITLE
[Submission]: PrizeVehicles

### ISSUE THREAD

**Issue by ShinyWasabi** [YimMenu-Lua/submission#54]
### Repository Name

PrizeVehicles

### Description

Allows you to edit prize vehicles such as Podium, LSCM, etc.

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/PrizeVehicles/invitations).
