### ISSUE TITLE
[Submission]: Billionare-Services

### ISSUE THREAD

**Issue by xesdoog** [YimMenu-Lua/submission#55]
### Repository Name

Billionare-Services

### Description

Lua script that provides VIP services for GTA V players.

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/Billionare-Services/invitations).
