### ISSUE TITLE
[Submission]: Pessiv2 but actually good and updated.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu-Lua/submission#56]
### Repository Name

Pesiv2-Updated

### Description

Pesiv2 but it's actually updated and uses YimMenu's GUI

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/Pesiv2-Updated/invitations).
