### ISSUE TITLE
[Submission]: Yim Menu

### ISSUE THREAD

**Issue by lYoril** [YimMenu-Lua/submission#59]
### Repository Name

YimMenu

### Description

YimMenu

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/YimMenu/invitations).

**Comment by Yimura** [comment]
@lYoril, I have removed your repository as having a Lua repo called YimMenu would be very confusing and misleading for people.
