### ISSUE TITLE
[Submission]: Script

### ISSUE THREAD

**Issue by lYoril** [YimMenu-Lua/submission#60]
### Repository Name

 YimMenu-Lua/Casino

### Description

Heist editor

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by Sumbledumble** [comment]
Repository Name
YimMenu-Lua/Casino

Description
Heist editor

ToS Agreement
 I agree to the Github ToS
External Linking
 I agree not to link externally
No Advertising
 I agree not to advertise for commercial gain
Paywalling
 I agree not to paywall features

**Comment by Yimura** [comment]
???
