### ISSUE TITLE
[Submission]: Removed vehicles 

### ISSUE THREAD

**Issue by visionary2709** [YimMenu-Lua/submission#62]
### Repository Name

Removed vehicles

### Description

Re-activate the option to purchase the removed vehicles through the web pages. 

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/Removed-vehicles/invitations).
