### ISSUE TITLE
[Submission]: Samurais Scripts

### ISSUE THREAD

**Issue by xesdoog** [YimMenu-Lua/submission#66]
### Repository Name

Samurais-Scripts

### Description

A base for a Lua script centered around roleplaying and having fun in a game full of ad bots and toxic cheaters.

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/Samurais-Scripts/invitations).
