### ISSUE TITLE
[Submission]: YimLLS

### ISSUE THREAD

**Issue by tupoy-ya** [YimMenu-Lua/submission#67]
### Repository Name

YimLLS

### Description

LuaLS meta files for the YimMenu API, only for script developers.

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/YimLLS/invitations).
