### ISSUE TITLE
[Submission]: G9EC

### ISSUE THREAD

**Issue by ShinyWasabi** [YimMenu-Lua/submission#72]
### Repository Name

G9EC

### Description

Enables next-gen exclusive (PlayStation 5 & Xbox Series X|S) clothing items in the store.

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/G9EC/invitations).
