### ISSUE TITLE
[Submission]: Phone Editor

### ISSUE THREAD

**Issue by celeronishe** [YimMenu-Lua/submission#73]
### Repository Name

Phone-Editor

### Description

A script that allows you to change the player's phone

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/Phone-Editor/invitations).
