### ISSUE TITLE
[Submission]: GoldenGets Menu

### ISSUE THREAD

**Issue by GoldenGets** [YimMenu-Lua/submission#74]
### Repository Name

GoldenGets-Menu

### Description

Lua script for YimMenu which is useful for your GTA Online progress

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/GoldenGets-Menu/invitations).
