### ISSUE TITLE
[Submission]: RankEditor

### ISSUE THREAD

**Issue by ShinyWasabi** [YimMenu-Lua/submission#77]
### Repository Name

RankEditor

### Description

Allows you to edit your character rank, LSCM REP Tier, and Arena War Sponsorship Tier.

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/RankEditor/invitations).
