### ISSUE TITLE
[Submission]: VehicleReward

### ISSUE THREAD

**Issue by janek420x** [YimMenu-Lua/submission#83]
### Repository Name

Vehicle Reward

### Description

Just don't know how this works, how to open this, and how to know when it's working

### ToS Agreement

- [X] I agree to the Github ToS

### External Linking

- [X] I agree not to link externally

### No Advertising

- [X] I agree not to advertise for commercial gain

### Paywalling

- [X] I agree not to paywall features

**Comment by YimNPC** [comment]
Success, your repository has been created!

You can accept the invite by checking your email or clicking [here](https://github.com/YimMenu-Lua/Vehicle-Reward/invitations).

**Comment by janek420x** [comment]
It should be a comment not a next script

**Comment by xesdoog** [comment]
> It should be a comment not a next script

This is the [submissions](https://github.com/YimMenu-Lua/submission/blob/master/README.md) repo. You shouldn't open any issues here unless you intend to create a new repository.

Issues regarding Lua scripts should be opened in their respective repositories. This is the [Vehicle Reward](https://github.com/YimMenu-Lua/VehicleReward) repository and [this is where you should've opened your issue](https://github.com/YimMenu-Lua/VehicleReward/issues).

> [!NOTE]
> A [similar question](https://github.com/YimMenu-Lua/VehicleReward/issues/1) to yours has already been answered.
